package com.moonstreamtech.lasttile

import android.util.Log
import com.google.firebase.Timestamp
import com.google.firebase.firestore.FirebaseFirestoreException
import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.ktx.Firebase
import kotlinx.coroutines.tasks.await
import java.util.Date
import java.util.concurrent.TimeUnit

/**
 * Username read / change layer on top of Firestore.
 *
 * Two collections are involved:
 *   - `users/{uid}`            — the player document, holds the current
 *                                displayName and lastUsernameChangeAt.
 *   - `usernames/{nameLower}`  — reservation docs that enforce uniqueness
 *                                of player-chosen names. Auto-assigned
 *                                "#NNNNNN" identifiers are NOT reserved
 *                                here (see [UserBootstrap.allocateNumericId]
 *                                which uses a separate `numericIds`
 *                                collection); [isAutoGeneratedName] is the
 *                                check used by [changeUsername] to skip the
 *                                old-reservation delete in that case.
 *
 * 30-day cooldown between changes, enforced inside the transaction so the
 * client cannot bypass it by racing two requests.
 */
object UsernameRepository {
    private const val TAG = "UsernameRepository"
    private val COOLDOWN_MS = TimeUnit.DAYS.toMillis(30)
    private val AUTO_NAME_REGEX = Regex("^#\\d{6}$")

    sealed class AvailabilityResult {
        object Available : AvailabilityResult()
        object Taken : AvailabilityResult()
        object NetworkError : AvailabilityResult()
    }

    sealed class ChangeResult {
        object Success : ChangeResult()
        object Taken : ChangeResult()
        data class CooldownActive(val daysRemaining: Int) : ChangeResult()
        object NetworkError : ChangeResult()
    }

    fun isAutoGeneratedName(name: String): Boolean = AUTO_NAME_REGEX.matches(name)

    suspend fun checkAvailability(name: String): AvailabilityResult {
        val key = name.trim().lowercase()
        if (key.isEmpty()) return AvailabilityResult.Taken
        return try {
            val snap = Firebase.firestore.collection("usernames").document(key).get().await()
            if (snap.exists()) AvailabilityResult.Taken else AvailabilityResult.Available
        } catch (e: Exception) {
            Log.w(TAG, "checkAvailability failed for $key", e)
            AvailabilityResult.NetworkError
        }
    }

    suspend fun changeUsername(newName: String): ChangeResult {
        val uid = UserBootstrap.uid ?: return ChangeResult.NetworkError
        val trimmed = newName.trim()
        if (trimmed.isEmpty()) return ChangeResult.Taken
        val newKey = trimmed.lowercase()
        val db = Firebase.firestore
        val userRef = db.collection("users").document(uid)
        val newRef = db.collection("usernames").document(newKey)

        // Local marker exceptions used to short-circuit the transaction
        // with a typed result without losing fidelity through wrapping.
        class CooldownSignal(val daysRemaining: Int) : RuntimeException()
        class TakenSignal : RuntimeException()

        return try {
            db.runTransaction { tx ->
                val userSnap = tx.get(userRef)
                val currentName = userSnap.getString("displayName") ?: ""
                val lastChangeTs = userSnap.getTimestamp("lastUsernameChangeAt")
                if (lastChangeTs != null) {
                    val elapsedMs = System.currentTimeMillis() - lastChangeTs.toDate().time
                    if (elapsedMs < COOLDOWN_MS) {
                        val remainingMs = COOLDOWN_MS - elapsedMs
                        // Round up so the user never sees "0 days" while
                        // the cooldown is technically still active.
                        val daysRemaining = ((remainingMs + TimeUnit.DAYS.toMillis(1) - 1) /
                            TimeUnit.DAYS.toMillis(1)).toInt().coerceAtLeast(1)
                        throw CooldownSignal(daysRemaining)
                    }
                }

                // Skip the read of the new-name reservation when the user
                // is renaming to (essentially) themselves — the lowercased
                // key is unchanged, so the doc already belongs to them.
                val oldKey = currentName.lowercase()
                val sameKey = oldKey == newKey
                val newSnap = tx.get(newRef)
                if (!sameKey && newSnap.exists()) {
                    throw TakenSignal()
                }

                // All reads complete; writes follow. Skip releasing the
                // old reservation when the previous name was auto-assigned
                // (it lives in numericIds, not usernames).
                if (currentName.isNotEmpty() && !isAutoGeneratedName(currentName) && !sameKey) {
                    val oldRef = db.collection("usernames").document(oldKey)
                    tx.delete(oldRef)
                }
                tx.set(newRef, mapOf("userId" to uid))
                tx.update(
                    userRef,
                    mapOf(
                        "displayName" to trimmed,
                        "lastUsernameChangeAt" to Timestamp(Date())
                    )
                )
                null
            }.await()
            Log.i(TAG, "Username changed to '$trimmed' for uid=$uid")
            ChangeResult.Success
        } catch (e: Exception) {
            // Unwrap our local marker exceptions, which Firestore wraps
            // in its own RuntimeException when thrown inside the lambda.
            val cause = e.cause ?: e
            when (cause) {
                is CooldownSignal -> ChangeResult.CooldownActive(cause.daysRemaining)
                is TakenSignal -> ChangeResult.Taken
                else -> {
                    if (cause is FirebaseFirestoreException) {
                        Log.w(TAG, "changeUsername Firestore error: ${cause.code}", cause)
                    } else {
                        Log.w(TAG, "changeUsername failed", e)
                    }
                    ChangeResult.NetworkError
                }
            }
        }
    }
}
