package com.moonstreamtech.lasttile

import android.util.Log
import com.google.firebase.firestore.FieldValue
import com.google.firebase.firestore.FirebaseFirestoreException
import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.ktx.Firebase
import kotlinx.coroutines.tasks.await
import java.util.concurrent.TimeUnit

/**
 * Username read / change layer on top of Firestore.
 *
 * Two collections are involved:
 *   - `users/{uid}`            — the player document, holds the current
 *                                displayName and lastUsernameChangeAt.
 *   - `usernames/{nameLower}`  — reservation docs that enforce uniqueness
 *                                of player-chosen names. Auto-assigned
 *                                "#NNNNNN" identifiers are NOT reserved
 *                                here (see [UserBootstrap.allocateNumericId]
 *                                which uses a separate `numericIds`
 *                                collection); [isAutoGeneratedName] is the
 *                                check used by [changeUsername] to skip the
 *                                old-reservation delete in that case.
 *
 * 30-day cooldown between changes, enforced inside the transaction so the
 * client cannot bypass it by racing two requests. [cooldownDaysRemaining]
 * is a pre-check the UI calls before opening the dialog so the user sees
 * a toast immediately instead of typing into a dialog whose Save will
 * always fail.
 */
object UsernameRepository {
    private const val TAG = "UsernameRepository"
    private val COOLDOWN_MS = TimeUnit.DAYS.toMillis(30)
    private val AUTO_NAME_REGEX = Regex("^#\\d{6}$")

    sealed class AvailabilityResult {
        object Available : AvailabilityResult()
        object Taken : AvailabilityResult()
        object NetworkError : AvailabilityResult()
    }

    sealed class ChangeResult {
        object Success : ChangeResult()
        object Taken : ChangeResult()
        data class CooldownActive(val daysRemaining: Int) : ChangeResult()
        object NetworkError : ChangeResult()
    }

    // Marker exceptions used to short-circuit the transaction with a typed
    // result without losing fidelity through Firestore's wrapping. Defined
    // at object scope so the cause-chain walk in the catch block can match
    // them with `is` regardless of how many layers of wrapping Firestore
    // applies (we've observed the chain go two levels deep on real devices).
    private class CooldownSignal(val daysRemaining: Int) : RuntimeException()
    private class TakenSignal : RuntimeException()

    fun isAutoGeneratedName(name: String): Boolean = AUTO_NAME_REGEX.matches(name)

    /**
     * Reads the current user doc and returns how many days remain on the
     * 30-day rename cooldown — 0 if the cooldown has expired or was
     * never started. Defensive: any exception (auth missing, network)
     * returns 0 so the UI doesn't block a legitimate rename behind a
     * pre-check that itself failed; the [changeUsername] transaction
     * is the authoritative gate.
     */
    suspend fun cooldownDaysRemaining(): Int {
        return try {
            val uid = UserBootstrap.uid ?: return 0
            val snapshot = Firebase.firestore.collection("users").document(uid).get().await()
            val timestamp = snapshot.getTimestamp("lastUsernameChangeAt") ?: return 0
            val elapsedMs = System.currentTimeMillis() - timestamp.toDate().time
            if (elapsedMs >= COOLDOWN_MS) {
                0
            } else {
                val remainingMs = COOLDOWN_MS - elapsedMs
                ((remainingMs + TimeUnit.DAYS.toMillis(1) - 1) /
                    TimeUnit.DAYS.toMillis(1)).toInt().coerceAtLeast(1)
            }
        } catch (e: Exception) {
            Log.w(TAG, "cooldownDaysRemaining failed", e)
            0
        }
    }

    suspend fun checkAvailability(name: String): AvailabilityResult {
        val key = name.trim().lowercase()
        if (key.isEmpty()) return AvailabilityResult.Taken
        return try {
            val snap = Firebase.firestore.collection("usernames").document(key).get().await()
            if (snap.exists()) AvailabilityResult.Taken else AvailabilityResult.Available
        } catch (e: Exception) {
            Log.w(TAG, "checkAvailability failed for $key", e)
            AvailabilityResult.NetworkError
        }
    }

    suspend fun changeUsername(newName: String): ChangeResult {
        val uid = UserBootstrap.uid ?: return ChangeResult.NetworkError
        val trimmed = newName.trim()
        if (trimmed.isEmpty()) return ChangeResult.Taken
        val newKey = trimmed.lowercase()
        val db = Firebase.firestore
        val userRef = db.collection("users").document(uid)
        val newRef = db.collection("usernames").document(newKey)

        return try {
            db.runTransaction { tx ->
                val userSnap = tx.get(userRef)
                val currentName = userSnap.getString("displayName") ?: ""
                val lastChangeTs = userSnap.getTimestamp("lastUsernameChangeAt")
                if (lastChangeTs != null) {
                    val elapsedMs = System.currentTimeMillis() - lastChangeTs.toDate().time
                    if (elapsedMs < COOLDOWN_MS) {
                        val remainingMs = COOLDOWN_MS - elapsedMs
                        // Round up so the user never sees "0 days" while
                        // the cooldown is technically still active.
                        val daysRemaining = ((remainingMs + TimeUnit.DAYS.toMillis(1) - 1) /
                            TimeUnit.DAYS.toMillis(1)).toInt().coerceAtLeast(1)
                        throw CooldownSignal(daysRemaining)
                    }
                }

                // Skip the read of the new-name reservation when the user
                // is renaming to (essentially) themselves — the lowercased
                // key is unchanged, so the doc already belongs to them.
                val oldKey = currentName.lowercase()
                val sameKey = oldKey == newKey
                val newSnap = tx.get(newRef)
                if (!sameKey && newSnap.exists()) {
                    throw TakenSignal()
                }

                // All reads complete; writes follow. Skip releasing the
                // old reservation when the previous name was auto-assigned
                // (it lives in numericIds, not usernames).
                if (currentName.isNotEmpty() && !isAutoGeneratedName(currentName) && !sameKey) {
                    val oldRef = db.collection("usernames").document(oldKey)
                    tx.delete(oldRef)
                }
                tx.set(newRef, mapOf("userId" to uid))
                tx.update(
                    userRef,
                    mapOf(
                        "displayName" to trimmed,
                        // Server timestamp avoids client clock issues:
                        // a device with a wrong clock can't write a past
                        // timestamp that immediately satisfies the next
                        // change's cooldown read.
                        "lastUsernameChangeAt" to FieldValue.serverTimestamp()
                    )
                )
                null
            }.await()
            Log.i(TAG, "Username changed to '$trimmed' for uid=$uid")
            ChangeResult.Success
        } catch (e: Throwable) {
            // Walk the entire cause chain — Firestore wraps lambda-thrown
            // exceptions one or more levels deep depending on platform
            // and SDK version. A single .cause unwrap was missing the
            // marker on real devices, which caused cooldown / taken
            // signals to silently fall through to NetworkError.
            var cur: Throwable? = e
            while (cur != null) {
                when (cur) {
                    is CooldownSignal -> return ChangeResult.CooldownActive(cur.daysRemaining)
                    is TakenSignal -> return ChangeResult.Taken
                }
                cur = cur.cause
            }
            if (e is FirebaseFirestoreException) {
                Log.w(TAG, "changeUsername Firestore error: ${e.code}", e)
            } else {
                Log.w(TAG, "changeUsername failed", e)
            }
            ChangeResult.NetworkError
        }
    }
}
